package bean;
// Generated 09/11/2023 13:54:16 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VendaprodutoEbg generated by hbm2java
 */
@Entity
@Table(name="vendaproduto_ebg"
    ,catalog="db_estefani_gimenez"
)
public class VendaprodutoEbg  implements java.io.Serializable {


     private int idvendaprodutoEbg;
     private ProdutoEbg produtoEbg;
     private VendaEbg vendaEbg;
     private VendedorEbg vendedorEbg;
     private int quantidadeEbg;
     private String valorunitEbg;

    public VendaprodutoEbg(int idvendaprodutoEbg, ProdutoEbg produtoEbg, VendaEbg vendaEbg, VendedorEbg vendedorEbg, int quantidadeEbg, String valorunitEbg) {
       this.idvendaprodutoEbg = idvendaprodutoEbg;
       this.produtoEbg = produtoEbg;
       this.vendaEbg = vendaEbg;
       this.vendedorEbg = vendedorEbg;
       this.quantidadeEbg = quantidadeEbg;
       this.valorunitEbg = valorunitEbg;
    }
   
     @Id 

    
    @Column(name="idvendaproduto_ebg", unique=true, nullable=false)
    public int getIdvendaprodutoEbg() {
        return this.idvendaprodutoEbg;
    }
    
    public void setIdvendaprodutoEbg(int idvendaprodutoEbg) {
        this.idvendaprodutoEbg = idvendaprodutoEbg;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produto_ebg", nullable=false)
    public ProdutoEbg getProdutoEbg() {
        return this.produtoEbg;
    }
    
    public void setProdutoEbg(ProdutoEbg produtoEbg) {
        this.produtoEbg = produtoEbg;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="venda", nullable=false)
    public VendaEbg getVendaEbg() {
        return this.vendaEbg;
    }
    
    public void setVendaEbg(VendaEbg vendaEbg) {
        this.vendaEbg = vendaEbg;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vendedor_ebg", nullable=false)
    public VendedorEbg getVendedorEbg() {
        return this.vendedorEbg;
    }
    
    public void setVendedorEbg(VendedorEbg vendedorEbg) {
        this.vendedorEbg = vendedorEbg;
    }

    
    @Column(name="quantidade_ebg", nullable=false)
    public int getQuantidadeEbg() {
        return this.quantidadeEbg;
    }
    
    public void setQuantidadeEbg(int quantidadeEbg) {
        this.quantidadeEbg = quantidadeEbg;
    }

    
    @Column(name="valorunit_ebg", nullable=false, length=80)
    public String getValorunitEbg() {
        return this.valorunitEbg;
    }
    
    public void setValorunitEbg(String valorunitEbg) {
        this.valorunitEbg = valorunitEbg;
    }




}


