package bean;
// Generated 13/09/2023 13:13:29 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendaEbg generated by hbm2java
 */
@Entity
@Table(name="venda_ebg"
    ,catalog="db_estefani_gimenez"
)
public class VendaEbg  implements java.io.Serializable {


     private int idvendaEbg;
     private ClienteEbg clienteEbg;
     private VendedorEbg vendedorEbg;
     private Date dataEbg;
     private String totalvendaEbg;
     private Set vendaprodutoEbgs = new HashSet(0);

    public VendaEbg() {
    }

	
    public VendaEbg(int idvendaEbg, ClienteEbg clienteEbg, VendedorEbg vendedorEbg, Date dataEbg, String totalvendaEbg) {
        this.idvendaEbg = idvendaEbg;
        this.clienteEbg = clienteEbg;
        this.vendedorEbg = vendedorEbg;
        this.dataEbg = dataEbg;
        this.totalvendaEbg = totalvendaEbg;
    }
    public VendaEbg(int idvendaEbg, ClienteEbg clienteEbg, VendedorEbg vendedorEbg, Date dataEbg, String totalvendaEbg, Set vendaprodutoEbgs) {
       this.idvendaEbg = idvendaEbg;
       this.clienteEbg = clienteEbg;
       this.vendedorEbg = vendedorEbg;
       this.dataEbg = dataEbg;
       this.totalvendaEbg = totalvendaEbg;
       this.vendaprodutoEbgs = vendaprodutoEbgs;
    }
   
     @Id 

    
    @Column(name="idvenda_ebg", unique=true, nullable=false)
    public int getIdvendaEbg() {
        return this.idvendaEbg;
    }
    
    public void setIdvendaEbg(int idvendaEbg) {
        this.idvendaEbg = idvendaEbg;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cliente_ebg", nullable=false)
    public ClienteEbg getClienteEbg() {
        return this.clienteEbg;
    }
    
    public void setClienteEbg(ClienteEbg clienteEbg) {
        this.clienteEbg = clienteEbg;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vendedor_ebg", nullable=false)
    public VendedorEbg getVendedorEbg() {
        return this.vendedorEbg;
    }
    
    public void setVendedorEbg(VendedorEbg vendedorEbg) {
        this.vendedorEbg = vendedorEbg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_ebg", nullable=false, length=10)
    public Date getDataEbg() {
        return this.dataEbg;
    }
    
    public void setDataEbg(Date dataEbg) {
        this.dataEbg = dataEbg;
    }

    
    @Column(name="totalvenda_ebg", nullable=false, length=45)
    public String getTotalvendaEbg() {
        return this.totalvendaEbg;
    }
    
    public void setTotalvendaEbg(String totalvendaEbg) {
        this.totalvendaEbg = totalvendaEbg;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vendaEbg")
    public Set getVendaprodutoEbgs() {
        return this.vendaprodutoEbgs;
    }
    
    public void setVendaprodutoEbgs(Set vendaprodutoEbgs) {
        this.vendaprodutoEbgs = vendaprodutoEbgs;
    }




}


